### ISSUE TITLE
Retry and cycle validators when REST requests fail.

### ISSUE THREAD

**Issue by switcheolytics** [Mai-Te-Pora/tradehub-python#13]
Through our build and testing of finding active validators to accept REST API requests, there are many instances where a Validator is believed to be active but in fact is not. See #9 as a reference.

This is causing many failed tests and issues with scripts. There needs to be a method to take failed REST requests and attempt different believed active validators to avoid process failure.

**Comment by switcheolytics** [comment]
#19 is attempting to introduce a client to help track this. Will need tests to ensure this is working as intended.

**Comment by switcheolytics** [comment]
Now that this has been approved and merged we need to roll it out to all network functions to be able to take advantage of the new functionality.

We should also be sure that the ability to specify a single Node IP also be available since there is some overhead to perform the network crawl.

**Comment by Devel484** [comment]
The websocket client could use this too. Sometimes a sentry allows REST requests(Port 5001) but deny was connections(Port 5000)

**Comment by switcheolytics** [comment]
#25 is the implementation of the functionality introduced in #19

**Comment by switcheolytics** [comment]
This is complete at this point from a network crawler perspective. I believe the WS retry functionality needs to be added.
